blank_issues_enabled: false
contact_links:
  - name: GitHub Security Issues/Bug Reports
    url: https://themoddersden.com/contact/
    about: Please report security vulnerabilities and bugs here (using one of the forms of contact available on my website).