name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
assignees: [
  "TheModdersDen"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
      render: markdown
    validations:
      required: true
  - type: textarea
    id: repository-url
    attributes:
      label: "Your repository URL"
      description: |
        Please enter your GitHub repository URL to provide additional context,
        if you created a repository based on this project. Otherwise, just 
        leave this field blank and skip it.
      placeholder: 'For example: https://github.com/USERNAME/REPO-NAME'
      render: text
    validations:
      required: false
  - type: textarea
    id: reprod-steps
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: markdown
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: markdown
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: textarea
    id: wgsm-version
    attributes:
      label: "WindowsGSM Version"
      description: What version of WindowsGSM are you seeing the problem on?
      placeholder: A specific version number or build (for example, 'v1.23.1' or 'build 1234')
      render: text
    validations:
      required: true
  - type: dropdown
    id: os-type
    attributes:
      label: "OS Type"
      description: What is/are the impacted operating system(s)?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
        - Other (please specify in the description)
    validations:
      required: true
  - type: checkboxes
    id: privacy
    attributes:
      label: "Privacy Acknowledgement"
      description: "Please confirm that you have read and agree to the terms and conditions."
      options:
        - label: "I understand that my question may be publicly visible."
          required: true
        - label: "I have read and agree to the terms and conditions (found in the 'TERMS_AND_CONDITIONS.md' file in the 'docs' directory)."
          required: true
        - label: "I understand that my question may be closed without notice, potentially without an answer."
          required: true
        - label: "I understand that my question may be removed, deleted, or otherwise altered without notice."
          required: true